// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev02_MVC_MovieArchive.Models;

#nullable disable

namespace Odev02_MVC_MovieArchive.Migrations
{
    [DbContext(typeof(MovieArchiveDbContext))]
    [Migration("20260924223957_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odev02_MVC_MovieArchive.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Çağan Irmak",
                            ReleaseYear = 2005,
                            Title = "Babam ve Oğlum"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Yavuz Turgul",
                            ReleaseYear = 1996,
                            Title = "Eşkıya"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Francis Ford Coppola",
                            ReleaseYear = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Ömer Faruk Sorak",
                            ReleaseYear = 2004,
                            Title = "G.O.R.A."
                        },
                        new
                        {
                            Id = 6,
                            Director = "Quentin Tarantino",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Yılmaz Erdoğan, Ömer Faruk Sorak",
                            ReleaseYear = 2001,
                            Title = "Vizontele"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Nuri Bilge Ceylan",
                            ReleaseYear = 2011,
                            Title = "Bir Zamanlar Anadolu'da"
                        },
                        new
                        {
                            Id = 10,
                            Director = "Christopher Nolan",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
