// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev01_MVC_Library.Models;

#nullable disable

namespace Odev01_MVC_Library.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odev01_MVC_Library.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mustafa Kemal Atatürk",
                            PageCount = 543,
                            Title = "Nutuk"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Fyodor Dostoyevski",
                            PageCount = 704,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Victor Hugo",
                            PageCount = 1724,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 4,
                            Author = "George Orwell",
                            PageCount = 352,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            Author = "José Mauro de Vasconcelos",
                            PageCount = 200,
                            Title = "Şeker Portakalı"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Sabahattin Ali",
                            PageCount = 160,
                            Title = "Kürk Mantolu Madonna"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Paulo Coelho",
                            PageCount = 184,
                            Title = "Simyacı"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Antoine de Saint-Exupéry",
                            PageCount = 112,
                            Title = "Küçük Prens"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Franz Kafka",
                            PageCount = 104,
                            Title = "Dönüşüm"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Oğuz Atay",
                            PageCount = 724,
                            Title = "Tutunamayanlar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
