// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev05_MVC_CafeMenu.Models;

#nullable disable

namespace Odev05_MVC_CafeMenu.Migrations
{
    [DbContext(typeof(CafeMenuDbContext))]
    partial class CafeMenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odev05_MVC_CafeMenu.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sıcak İçecek",
                            Name = "Türk Kahvesi",
                            Price = 75
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sıcak İçecek",
                            Name = "Espresso",
                            Price = 80
                        },
                        new
                        {
                            Id = 3,
                            Category = "Soğuk İçecek",
                            Name = "Iced Latte",
                            Price = 110
                        },
                        new
                        {
                            Id = 4,
                            Category = "Soğuk İçecek",
                            Name = "Ev Yapımı Limonata",
                            Price = 95
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tatlı",
                            Name = "San Sebastian Cheesecake",
                            Price = 180
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tatlı",
                            Name = "Tiramisu",
                            Price = 160
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sıcak İçecek",
                            Name = "Demleme Çay",
                            Price = 35
                        },
                        new
                        {
                            Id = 8,
                            Category = "Soğuk İçecek",
                            Name = "Ice Americano",
                            Price = 100
                        },
                        new
                        {
                            Id = 9,
                            Category = "Sıcak İçecek",
                            Name = "Sıcak Çikolata",
                            Price = 120
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tatlı",
                            Name = "Havuçlu Kek",
                            Price = 130
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
