// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev06_MVC_TravelGuide.Models;

#nullable disable

namespace Odev06_MVC_TravelGuide.Migrations
{
    [DbContext(typeof(TravelGuideDbContext))]
    [Migration("20260925192136_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odev06_MVC_TravelGuide.Models.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntryFee")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            EntryFee = 1500,
                            Name = "Topkapı Sarayı Müzesi"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ankara",
                            EntryFee = 0,
                            Name = "Anıtkabir"
                        },
                        new
                        {
                            Id = 3,
                            City = "İzmir",
                            EntryFee = 1250,
                            Name = "Efes Antik Kenti"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            EntryFee = 900,
                            Name = "Yerebatan Sarnıcı"
                        },
                        new
                        {
                            Id = 5,
                            City = "Trabzon",
                            EntryFee = 450,
                            Name = "Sümela Manastırı"
                        },
                        new
                        {
                            Id = 6,
                            City = "Antalya",
                            EntryFee = 50,
                            Name = "Düden Şelalesi"
                        },
                        new
                        {
                            Id = 7,
                            City = "Denizli",
                            EntryFee = 700,
                            Name = "Pamukkale Travertenleri"
                        },
                        new
                        {
                            Id = 8,
                            City = "Ankara",
                            EntryFee = 0,
                            Name = "Atatürk Orman Çiftliği"
                        },
                        new
                        {
                            Id = 9,
                            City = "Nevşehir",
                            EntryFee = 1000,
                            Name = "Göreme Açık Hava Müzesi"
                        },
                        new
                        {
                            Id = 10,
                            City = "İstanbul",
                            EntryFee = 0,
                            Name = "Emirgan Korusu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
