// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Odev04_MVC_GymMembers.Models;

#nullable disable

namespace Odev04_MVC_GymMembers.Migrations
{
    [DbContext(typeof(GymMembersDbContext))]
    [Migration("20260925183233_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Odev04_MVC_GymMembers.Models.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberShipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            FullName = "Ahmet Yılmaz",
                            MemberShipType = "Aylık"
                        },
                        new
                        {
                            Id = 2,
                            Age = 34,
                            FullName = "Ayşe Kaya",
                            MemberShipType = "Yıllık"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            FullName = "Mehmet Demir",
                            MemberShipType = "3 Aylık"
                        },
                        new
                        {
                            Id = 4,
                            Age = 41,
                            FullName = "Zeynep Çelik",
                            MemberShipType = "Aylık"
                        },
                        new
                        {
                            Id = 5,
                            Age = 29,
                            FullName = "Can Öztürk",
                            MemberShipType = "Yıllık"
                        },
                        new
                        {
                            Id = 6,
                            Age = 25,
                            FullName = "Elif Şahin",
                            MemberShipType = "3 Aylık"
                        },
                        new
                        {
                            Id = 7,
                            Age = 33,
                            FullName = "Burak Arslan",
                            MemberShipType = "Aylık"
                        },
                        new
                        {
                            Id = 8,
                            Age = 37,
                            FullName = "Seda Aydın",
                            MemberShipType = "Yıllık"
                        },
                        new
                        {
                            Id = 9,
                            Age = 20,
                            FullName = "Emre Yıldız",
                            MemberShipType = "3 Aylık"
                        },
                        new
                        {
                            Id = 10,
                            Age = 31,
                            FullName = "Merve Koç",
                            MemberShipType = "Yıllık"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
